### ISSUE TITLE
Not working with facebook-ios-sdk 4.0

### ISSUE THREAD

**Issue by royherma** [combinatorial/DBFBProfilePictureView#24]
Initially getting FacebookSDK/FacebookSDK.h file not found in DBFB header file

**Comment by combinatorial** [comment]
Thanks for letting me know. I have no time to work on this at the moment, but will happily accepts a pull request.

**Comment by royherma** [comment]
I'm working on a big project that utilizes DBFB, just wanted to say thanks, its been a huge asset for me! Otherwise, once I update my app for fb ios sdk 4.0, ill fix up DBFB and send you a pull request.

**Comment by combinatorial** [comment]
Thanks, I appreciate it, and glad it has helped!

**Comment by combinatorial** [comment]
You may want to take a look at this... https://github.com/combinatorial/DBFBProfilePictureView/pull/25

**Comment by combinatorial** [comment]
fixed in 1.6
